/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c HardNotificationsAdaptor interfaces/hardnotifications.xml -a hardnotificationsadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "hardnotificationsadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class HardNotificationsAdaptor
 */

HardNotificationsAdaptor::HardNotificationsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

HardNotificationsAdaptor::~HardNotificationsAdaptor()
{
    // destructor
}

void HardNotificationsAdaptor::showHardNotification(const QString &message, uint alarmId)
{
    // handle method call com.meego.ux.hardnotification.showHardNotification
    QMetaObject::invokeMethod(parent(), "showHardNotification", Q_ARG(QString, message), Q_ARG(uint, alarmId));
}

