/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c HardNotificationsAdaptor interfaces/hardnotifications.xml -a hardnotificationsadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef HARDNOTIFICATIONSADAPTOR_H_1302639562
#define HARDNOTIFICATIONSADAPTOR_H_1302639562

#include <QObject>
#include <QDBusAbstractAdaptor>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.meego.ux.hardnotification
 */
class HardNotificationsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meego.ux.hardnotifications")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meego.ux.hardnotifications\">\n"
"    <method name=\"showHardNotification\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"message\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"alarmId\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    HardNotificationsAdaptor(QObject *parent);
    virtual ~HardNotificationsAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void showHardNotification(const QString &message, uint alarmId);
Q_SIGNALS: // SIGNALS
};

#endif
