/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c StatusIndicatorMenuAdaptor interfaces/statusindicatormenu.xml -a statusindicatormenuadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STATUSINDICATORMENUADAPTOR_H_1299117732
#define STATUSINDICATORMENUADAPTOR_H_1299117732

#include <QObject>
#include <QDBusAbstractAdaptor>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.meego.core.MStatusIndicatorMenu
 */
class StatusIndicatorMenuAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meego.core.MStatusIndicatorMenu")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meego.core.MStatusIndicatorMenu\">\n"
"    <method name=\"open\"/>\n"
"  </interface>\n"
        "")
public:
    StatusIndicatorMenuAdaptor(QObject *parent);
    virtual ~StatusIndicatorMenuAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void open();
Q_SIGNALS: // SIGNALS
};

#endif
