/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c UdiskProxy -p udiskproxy.h:udiskproxy.cpp ./interfaces/org.freedesktop.UDisks.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef UDISKPROXY_H_1311184821
#define UDISKPROXY_H_1311184821

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.UDisks
 */
class UdiskProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.UDisks"; }

public:
    UdiskProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~UdiskProxy();

public Q_SLOTS: // METHODS
    void triggerAutoActivation();

Q_SIGNALS: // SIGNALS
    void DeviceAdded(const QDBusObjectPath &device);
    void DeviceChanged(const QDBusObjectPath &device);
    void DeviceRemoved(const QDBusObjectPath &device);
};

namespace org {
  namespace freedesktop {
    typedef ::UdiskProxy UDisks;
  }
}
#endif
