#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 2):
	print "Usage: %s USERID" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SessionBus()

manager = dbus.Interface(bus.get_object('com.meego.core.MNotificationManager', 
					'/notificationmanager'),
					'com.meego.core.MNotificationManager')

print manager.notificationListWithIdentifiers(sys.argv[1])
