#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 3):
	print "Usage: %s USERID NOTIFICATIONID" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SessionBus()

manager = dbus.Interface(bus.get_object('com.meego.core.MNotificationManager', 
					'/notificationmanager'),
					'com.meego.core.MNotificationManager')

print manager.removeNotification(sys.argv[1], sys.argv[2])
